language:
- objective-c
- c++

compiler:
- clang

sudo: false
os: osx

matrix:
  include:
    - osx_image: xcode7.3
      env: CONFIG=Debug
    - osx_image: xcode7.3
      env: CONFIG=Release
    - osx_image: xcode8.3
      env: CONFIG=Debug
    - osx_image: xcode8.3
      env: CONFIG=Release
    - osx_image: xcode9
      env: CONFIG=Debug
    - osx_image: xcode9
      env: CONFIG=Release

script:
- mkdir build
- cd build
- cmake -G Xcode ..
- cmake --build . --config ${CONFIG} | sed 's/-Wl,-.*//g'
- ctest -C ${CONFIG} . -V
- cd ..
- PACKAGE_NAME=`echo $TRAVIS_REPO_SLUG | sed 's/.*\///g'`
- PACKAGE_REV=`echo $TRAVIS_COMMIT | sed -e 's/^[[:alnum:]]\{7\}/&-/g' | sed 's/-.*//'`
- mkdir $PACKAGE_NAME
- if [ -e package-info.json ]; then cp package-info.json $PACKAGE_NAME; fi
- for f in *.md; do [ -e "$f" ] && cp "$f" $PACKAGE_NAME ; done
- if [ -e icon.png ]; then cp icon.png $PACKAGE_NAME; fi
- if [ -e CMakeLists.txt ]; then cp CMakeLists.txt $PACKAGE_NAME; fi
- if [ -d code ]; then cp -r code $PACKAGE_NAME; fi
- if [ -d docs ]; then cp -r docs $PACKAGE_NAME; fi
- if [ -d examples ]; then cp -r examples $PACKAGE_NAME; fi
- if [ -d extensions ]; then cp -r extensions $PACKAGE_NAME; fi
- if [ -d externals ]; then cp -r externals $PACKAGE_NAME; fi
- if [ -d extras ]; then cp -r extras $PACKAGE_NAME; fi
- if [ -d help ]; then cp -r help $PACKAGE_NAME; fi
- if [ -d init ]; then cp -r init $PACKAGE_NAME; fi
- if [ -d java-classes ]; then cp -r java-classes $PACKAGE_NAME; fi
- if [ -d java-doc ]; then cp -r java-doc $PACKAGE_NAME; fi
- if [ -d javascript ]; then cp -r javascript $PACKAGE_NAME; fi
- if [ -d jsui ]; then cp -r jsui $PACKAGE_NAME; fi
- if [ -d media ]; then cp -r media $PACKAGE_NAME; fi
- if [ -d misc ]; then cp -r misc $PACKAGE_NAME; fi
- if [ -d patchers ]; then cp -r patchers $PACKAGE_NAME; fi
- if [ -d support ]; then cp -r support $PACKAGE_NAME; fi
- if [ -d source ]; then cp -r source $PACKAGE_NAME; fi
- if [ -d tests ]; then cp -r tests $PACKAGE_NAME; fi
- if [ -e $PACKAGE_NAME/ReadMe-Public.md ]; then rm -f $PACKAGE_NAME/ReadMe.md; mv $PACKAGE_NAME/ReadMe-Public.md $PACKAGE_NAME/ReadMe.md; fi
- mkdir dist
- CONFIG_LOWERCASE=`echo $CONFIG | tr '[A-Z]' '[a-z]'`
- zip -r dist/$PACKAGE_NAME-mac-$PACKAGE_REV-$CONFIG_LOWERCASE.zip $PACKAGE_NAME

deploy:
  provider: s3
  access_key_id: AKIAIWE3SI2TMXC5AJBA
  secret_access_key:
    secure: "JykP00oi4o7A10flyDMILXdJ7zBd7vTlRpIeS01pqQ0wFYJGxDxNlVqVsR7wI/0Je6sHAPbB77rJFIz/iRgaOXUNxPOqNeVwCIQgabnFvM+GeBxYqabgHDUGyxwbLIBma5iOzDedibeyvpQzNiwIAeEZnjcUoEXCo5L4jerYHSPDoC5X2hCRhz913PfXdiTIRKdHMrJVPOzbnQew3q0qCRGzslELKrNtwtfXbAqShmTPoYwrT50vtavvazqu2h8YrNhqZ6oL9778anjshdgrR3/q+X0j0iY602SVKPcL2vM7f6GVKZrq6rMjprJpymzCiWuA1xn+Ar+eKTF2A9/z6kPiYKn7QSG56nEFnjibqcOjfJBIxhOl7pV8geoZDjEigX3RYD9WChki35mZrZ38SC2UTMuhyjI1nI8wQPsNYIWGtjCfcWTRUujHRoMr9WkLLLCPhY6vyv9eUU01SBMN6dby8mFqz9vwBHUvuhz/O/+El2csScCyM9YEbZ46v0cNToME0HkPoyx0x7ZzPfhM0eBxIq7iFSM3h6HHI22xo3x8Csp2Qv2GIWY0PF+IsnB3y5tJmtrWvnNZZCketWCK2Hj+1W3yrHN3DgDWlffjklG87ePQdXb98sEHKj4MARWf87QE+uBYG+kR1TqUquduoQa4JulI3AHdEJfZ25XQYuo="
  bucket: cycling74-ci
  skip_cleanup: true
  local-dir: dist
  upload-dir: min-devkit
  acl: public_read
  on:
    repo: Cycling74/min-devkit
    all_branches: true
